# Generated by Django 4.2.15 on 2024-09-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='users/avatars/default.png', upload_to='users/avatar', verbose_name='avatar'),
        ),
    ]
