# Generated by Django 4.2.15 on 2024-09-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Image'), (2, 'Video')], null=True, verbose_name='media type'),
        ),
    ]
