# Generated by Django 4.2.15 on 2024-08-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude')),
                ('long', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
            },
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('name', 'lat', 'long'), name='unique_location'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('lat', 'long')},
        ),
    ]
