# Generated by Django 4.2.15 on 2024-08-25 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='location',
            name='unique_location',
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set(),
        ),
    ]
