# Generated by Django 4.2.15 on 2024-08-31 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_remove_location_unique_location_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('name', 'lat', 'long')},
        ),
    ]
