# Generated by Django 4.2.15 on 2024-09-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Like'), (2, 'Comment'), (3, 'Follow'), (4, 'Save'), (5, 'Mention'), (6, 'Accept request'), (7, 'Follow request')], verbose_name='notification type'),
        ),
    ]
