# Generated by Django 4.2.15 on 2024-09-05 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created_at',), 'verbose_name': 'notification', 'verbose_name_plural': 'notifications'},
        ),
    ]
